"""Python APIs for Asterion replay analysis and measured inference."""

from __future__ import annotations

# `os` and `Path` are imported under private aliases so that the loader shim
# below does not publish `asterion.os` and `asterion.Path` as part of the public
# API. `sys` keeps its own name because mypy only recognises a platform guard
# written literally as `sys.platform`, and the shim needs that narrowing to
# type-check on non-Windows hosts where `os.add_dll_directory` does not exist.
import os as _os
import sys
from pathlib import Path as _Path


def _windows_dll_directories() -> list[_Path]:
    """Directories to search for the compiler runtime DLLs the extension needs.

    Since Python 3.8 the Windows loader ignores ``PATH`` for extension
    dependencies, so the directory holding ``libstdc++`` and ``libgcc`` has to be
    registered explicitly. ``ASTERION_DLL_DIR`` is checked first so any toolchain
    layout works; the remaining entries are conveniences for the common cases.
    """

    configured = _os.environ.get("ASTERION_DLL_DIR", "").split(_os.pathsep)
    directories = [_Path(entry) for entry in configured if entry]
    directories += [
        _Path(sys.base_prefix),
        _Path(sys.executable).resolve().parent,
        _Path.home() / "msys64" / "ucrt64" / "bin",
        _Path("C:/msys64/ucrt64/bin"),
    ]
    return directories


if sys.platform == "win32":  # pragma: no cover - Windows loader setup.
    for _dll_dir in _windows_dll_directories():
        if _dll_dir.is_dir():
            _os.add_dll_directory(str(_dll_dir))

try:
    from . import _native  # noqa: F401 - probes that the extension loads
except ImportError as exc:  # pragma: no cover - exercised when extension is not built.
    _hint = (
        " On Windows, set ASTERION_DLL_DIR to the directory holding the compiler"
        " runtime DLLs if the extension is built but fails to load."
        if _os.name == "nt"
        else ""
    )
    raise ImportError(
        "Asterion Python bindings are not built. Configure with "
        "-DASTERION_BUILD_PYTHON=ON, build the CMake project, and put "
        "<build>/python on PYTHONPATH." + _hint
    ) from exc

from ._native import (
    AggregateReplayConfig,
    AggregateReplaySummary,
    AuditManifest,
    AuditManifestFileEntry,
    AuditManifestIssue,
    AuditManifestIssueType,
    AuditManifestResult,
    AuditManifestSignature,
    AuditManifestVerification,
    BrokerEventType,
    BrokerOrderState,
    BrokerSessionEvent,
    BrokerSessionSnapshot,
    CancelOrderRequest,
    DisconnectOrderPolicy,
    EventLogFormat,
    EventLogReadResult,
    EventLogWriteResult,
    ExecType,
    ExecutionReport,
    FeatureExtractor,
    FeatureVector,
    InferenceBackend,
    InferenceDecision,
    InferencePolicy,
    InferencePolicyResult,
    InferenceResult,
    L2Level,
    L2View,
    LinearModel,
    MarketDataEvent,
    MarketEventType,
    MatchingEngine,
    NewOrderRequest,
    Order,
    OrderBook,
    OrderStatus,
    OrderType,
    PortfolioBreach,
    PortfolioCheckResult,
    PortfolioRiskLimits,
    PortfolioRiskMonitor,
    PortfolioSnapshot,
    RateLimitMode,
    RejectReason,
    ReplaceOrderRequest,
    ReplayConfig,
    ReplayDiagnostic,
    ReplayDiagnosticSeverity,
    ReplayParityReport,
    ReplayResult,
    ReplayValidationMode,
    RiskAuditEntry,
    RiskAuditLogFormat,
    RiskAuditTrail,
    RiskAuditVerificationResult,
    RiskExposureSnapshot,
    RiskGateway,
    RiskLimits,
    RiskResult,
    SessionConnectionState,
    Side,
    SimulatedBrokerSession,
    SpscBackpressurePolicy,
    SpscReplayConfig,
    SpscReplayResult,
    SpscReplayStats,
    SymbolParityEntry,
    SymbolReplaySummary,
    TimeInForce,
    audit_manifest_issue_type_to_string,
    broker_event_type_to_string,
    broker_order_state_to_string,
    checksum_diagnostics,
    checksum_events,
    checksum_execution_reports,
    choose_event_log_format_for_path,
    compare_replay_parity,
    compare_replay_parity_file,
    describe_replay_parity,
    detect_event_log_format,
    diagnostic_severity_to_string,
    disconnect_order_policy_to_string,
    evaluate_inference_policy,
    event_log_format_to_string,
    execution_report_checksum,
    final_book_checksum,
    generate_audit_manifest,
    inference_backend_status,
    inference_backend_to_string,
    inference_decision_to_string,
    market_data_event_to_csv,
    market_event_type_to_string,
    measure_linear_inference,
    onnx_runtime_available,
    parse_audit_manifest,
    parse_event_log_format,
    portfolio_breach_to_string,
    rate_limit_mode_to_string,
    read_audit_manifest,
    read_event_log,
    replay_by_symbol,
    replay_events,
    replay_file,
    replay_file_by_symbol,
    replay_file_shared_by_symbol,
    replay_shared_by_symbol,
    risk_audit_log_format_to_string,
    run_spsc_replay,
    run_spsc_replay_steady_state,
    serialize_audit_manifest,
    session_connection_state_to_string,
    side_to_string,
    verify_audit_manifest,
    verify_risk_audit_logs,
    write_audit_manifest,
    write_event_log,
)
from .aggregate import aggregate_by_symbol
from .benchmarks import load_benchmark_json, summarise_benchmark_json
from .event_log import convert_log, detect_format, load_log, write_log
from .regression import (
    BenchmarkComparison,
    BenchmarkDelta,
    BenchmarkMetric,
    BenchmarkSummary,
    LatencyBudgetStageSummary,
    LatencyBudgetSummary,
    benchmark_summary_to_dict,
    compare_benchmarks,
    comparison_to_dict,
    format_benchmark_summary_text,
    format_comparison_text,
    format_latency_budget_text,
    latency_budget_summary_to_dict,
    load_benchmark_metrics,
    summarise_benchmarks,
    summarise_latency_budget,
)
from .replay import (
    collect_diagnostics,
    diagnostics_checksum_for,
    execution_report_checksum_for,
    final_book_checksum_for,
    run_replay,
    shared_replay_fuzz_summary,
)

__all__ = [
    "AggregateReplayConfig",
    "AggregateReplaySummary",
    "AuditManifest",
    "AuditManifestFileEntry",
    "AuditManifestIssue",
    "AuditManifestIssueType",
    "AuditManifestResult",
    "AuditManifestSignature",
    "AuditManifestVerification",
    "BenchmarkComparison",
    "BenchmarkDelta",
    "BenchmarkMetric",
    "BenchmarkSummary",
    "BrokerEventType",
    "BrokerOrderState",
    "BrokerSessionEvent",
    "BrokerSessionSnapshot",
    "CancelOrderRequest",
    "DisconnectOrderPolicy",
    "EventLogFormat",
    "EventLogReadResult",
    "EventLogWriteResult",
    "ExecType",
    "ExecutionReport",
    "FeatureExtractor",
    "FeatureVector",
    "InferenceBackend",
    "InferenceDecision",
    "InferencePolicy",
    "InferencePolicyResult",
    "InferenceResult",
    "L2Level",
    "L2View",
    "LatencyBudgetStageSummary",
    "LatencyBudgetSummary",
    "LinearModel",
    "MarketDataEvent",
    "MarketEventType",
    "MatchingEngine",
    "NewOrderRequest",
    "Order",
    "OrderBook",
    "OrderStatus",
    "OrderType",
    "PortfolioBreach",
    "PortfolioCheckResult",
    "PortfolioRiskLimits",
    "PortfolioRiskMonitor",
    "PortfolioSnapshot",
    "RateLimitMode",
    "RejectReason",
    "ReplaceOrderRequest",
    "ReplayConfig",
    "ReplayDiagnostic",
    "ReplayDiagnosticSeverity",
    "ReplayParityReport",
    "ReplayResult",
    "ReplayValidationMode",
    "RiskAuditEntry",
    "RiskAuditLogFormat",
    "RiskAuditTrail",
    "RiskAuditVerificationResult",
    "RiskExposureSnapshot",
    "RiskGateway",
    "RiskLimits",
    "RiskResult",
    "SessionConnectionState",
    "Side",
    "SimulatedBrokerSession",
    "SpscBackpressurePolicy",
    "SpscReplayConfig",
    "SpscReplayResult",
    "SpscReplayStats",
    "SymbolParityEntry",
    "SymbolReplaySummary",
    "TimeInForce",
    "aggregate_by_symbol",
    "audit_manifest_issue_type_to_string",
    "benchmark_summary_to_dict",
    "broker_event_type_to_string",
    "broker_order_state_to_string",
    "checksum_diagnostics",
    "checksum_events",
    "checksum_execution_reports",
    "choose_event_log_format_for_path",
    "collect_diagnostics",
    "compare_benchmarks",
    "compare_replay_parity",
    "compare_replay_parity_file",
    "comparison_to_dict",
    "convert_log",
    "describe_replay_parity",
    "detect_event_log_format",
    "detect_format",
    "diagnostic_severity_to_string",
    "diagnostics_checksum_for",
    "disconnect_order_policy_to_string",
    "evaluate_inference_policy",
    "event_log_format_to_string",
    "execution_report_checksum",
    "execution_report_checksum_for",
    "final_book_checksum",
    "final_book_checksum_for",
    "format_benchmark_summary_text",
    "format_comparison_text",
    "format_latency_budget_text",
    "generate_audit_manifest",
    "inference_backend_status",
    "inference_backend_to_string",
    "inference_decision_to_string",
    "latency_budget_summary_to_dict",
    "load_benchmark_json",
    "load_benchmark_metrics",
    "load_log",
    "market_data_event_to_csv",
    "market_event_type_to_string",
    "measure_linear_inference",
    "onnx_runtime_available",
    "parse_audit_manifest",
    "parse_event_log_format",
    "portfolio_breach_to_string",
    "rate_limit_mode_to_string",
    "read_audit_manifest",
    "read_event_log",
    "replay_by_symbol",
    "replay_events",
    "replay_file",
    "replay_file_by_symbol",
    "replay_file_shared_by_symbol",
    "replay_shared_by_symbol",
    "risk_audit_log_format_to_string",
    "run_replay",
    "run_spsc_replay",
    "run_spsc_replay_steady_state",
    "serialize_audit_manifest",
    "session_connection_state_to_string",
    "shared_replay_fuzz_summary",
    "side_to_string",
    "summarise_benchmark_json",
    "summarise_benchmarks",
    "summarise_latency_budget",
    "verify_audit_manifest",
    "verify_risk_audit_logs",
    "write_audit_manifest",
    "write_event_log",
    "write_log",
]
