"""Python APIs for Asterion replay analysis and measured inference."""

from __future__ import annotations

try:
    from . import _native
except ImportError as exc:  # pragma: no cover - exercised when extension is not built.
    raise ImportError(
        "Asterion Python bindings are not built. Configure with "
        "-DASTERION_BUILD_PYTHON=ON, build the CMake project, and put "
        "<build>/python on PYTHONPATH."
    ) from exc

from ._native import (
    AggregateReplayConfig,
    AggregateReplaySummary,
    EventLogFormat,
    EventLogReadResult,
    EventLogWriteResult,
    ExecType,
    ExecutionReport,
    FeatureExtractor,
    FeatureVector,
    InferenceDecision,
    InferencePolicy,
    InferencePolicyResult,
    InferenceResult,
    L2Level,
    L2View,
    LinearModel,
    MarketDataEvent,
    MarketEventType,
    Order,
    OrderBook,
    OrderStatus,
    RejectReason,
    ReplayConfig,
    ReplayDiagnostic,
    ReplayDiagnosticSeverity,
    ReplayResult,
    Side,
    SymbolReplaySummary,
    TorchScriptModel,
    checksum_diagnostics,
    checksum_events,
    checksum_execution_reports,
    choose_event_log_format_for_path,
    detect_event_log_format,
    diagnostic_severity_to_string,
    evaluate_inference_policy,
    event_log_format_to_string,
    execution_report_checksum,
    final_book_checksum,
    inference_decision_to_string,
    market_data_event_to_csv,
    market_event_type_to_string,
    measure_linear_inference,
    parse_event_log_format,
    read_event_log,
    replay_by_symbol,
    replay_events,
    replay_file,
    replay_file_by_symbol,
    side_to_string,
    write_event_log,
)
from .aggregate import aggregate_by_symbol
from .benchmarks import load_benchmark_json, summarise_benchmark_json, summarise_benchmark_text
from .event_log import convert_log, detect_format, load_log, write_log
from .regression import (
    BenchmarkComparison,
    BenchmarkDelta,
    BenchmarkMetric,
    BenchmarkSummary,
    LatencyBudgetStageSummary,
    LatencyBudgetSummary,
    benchmark_summary_to_dict,
    compare_benchmarks,
    comparison_to_dict,
    format_benchmark_summary_text,
    format_comparison_text,
    format_latency_budget_text,
    latency_budget_summary_to_dict,
    load_benchmark_metrics,
    summarise_benchmarks,
    summarise_latency_budget,
)
from .replay import (
    collect_diagnostics,
    diagnostics_checksum_for,
    execution_report_checksum_for,
    final_book_checksum_for,
    run_replay,
)

__all__ = [
    "AggregateReplayConfig",
    "AggregateReplaySummary",
    "BenchmarkComparison",
    "BenchmarkDelta",
    "BenchmarkMetric",
    "BenchmarkSummary",
    "EventLogFormat",
    "EventLogReadResult",
    "EventLogWriteResult",
    "ExecType",
    "ExecutionReport",
    "FeatureExtractor",
    "FeatureVector",
    "InferenceDecision",
    "InferencePolicy",
    "InferencePolicyResult",
    "InferenceResult",
    "L2Level",
    "L2View",
    "LatencyBudgetStageSummary",
    "LatencyBudgetSummary",
    "LinearModel",
    "MarketDataEvent",
    "MarketEventType",
    "Order",
    "OrderBook",
    "OrderStatus",
    "RejectReason",
    "ReplayConfig",
    "ReplayDiagnostic",
    "ReplayDiagnosticSeverity",
    "ReplayResult",
    "Side",
    "SymbolReplaySummary",
    "TorchScriptModel",
    "aggregate_by_symbol",
    "benchmark_summary_to_dict",
    "checksum_diagnostics",
    "checksum_events",
    "checksum_execution_reports",
    "choose_event_log_format_for_path",
    "collect_diagnostics",
    "compare_benchmarks",
    "comparison_to_dict",
    "convert_log",
    "detect_event_log_format",
    "detect_format",
    "diagnostic_severity_to_string",
    "diagnostics_checksum_for",
    "evaluate_inference_policy",
    "event_log_format_to_string",
    "execution_report_checksum",
    "execution_report_checksum_for",
    "final_book_checksum",
    "final_book_checksum_for",
    "format_benchmark_summary_text",
    "format_comparison_text",
    "format_latency_budget_text",
    "inference_decision_to_string",
    "latency_budget_summary_to_dict",
    "load_benchmark_json",
    "load_benchmark_metrics",
    "load_log",
    "market_data_event_to_csv",
    "market_event_type_to_string",
    "measure_linear_inference",
    "parse_event_log_format",
    "read_event_log",
    "replay_by_symbol",
    "replay_events",
    "replay_file",
    "replay_file_by_symbol",
    "run_replay",
    "side_to_string",
    "summarise_benchmark_json",
    "summarise_benchmark_text",
    "summarise_benchmarks",
    "summarise_latency_budget",
    "write_event_log",
    "write_log",
]
