#!/usr/bin/env python3
"""Generate the tiny deterministic ONNX identity fixture used by Asterion tests.

The checked-in fixture ``data/fixtures/identity_1x4.onnx.b64`` is a base64-encoded
ONNX model with a single ``Identity`` node, input ``input`` of shape ``[1, 4]``
(float32) and an identically shaped output ``output``. It is intentionally tiny
(141 bytes decoded) and license-safe: it is a hand-described graph, not a trained
or third-party model. Tests decode it only when built with a real ONNX Runtime
(``ASTERION_HAVE_ONNXRUNTIME``); otherwise the deterministic LinearModel fallback
path is exercised instead.

This script documents exactly how that fixture was produced. It requires the
optional ``onnx`` Python package (it is NOT a default test/CI dependency):

    python -m pip install onnx
    python scripts/generate_onnx_fixture.py --output data/fixtures/identity_1x4.onnx.b64

Use ``--verify`` to regenerate in memory and assert byte-for-byte equality with the
checked-in fixture without overwriting it.

The identity model returns its input unchanged. The C++ ``OnnxModel`` reads the
first output element, so scoring a feature vector returns its first feature; the
unit tests assert exactly that deterministic behaviour.
"""

from __future__ import annotations

import argparse
import base64
import pathlib
import sys

# These constants reproduce the checked-in fixture exactly. Changing any of them
# changes the fixture bytes and would require re-running the ONNX Runtime tests.
IR_VERSION = 8
PRODUCER_NAME = "asterion"
PRODUCER_VERSION = "phase8"
GRAPH_NAME = "asterion_identity_fixture"
NODE_NAME = "identity"
OPSET_VERSION = 13
INPUT_NAME = "input"
OUTPUT_NAME = "output"
INPUT_SHAPE = [1, 4]

DEFAULT_OUTPUT = pathlib.Path("data/fixtures/identity_1x4.onnx.b64")


def build_model_bytes() -> bytes:
    """Build the identity ONNX model and return its serialized protobuf bytes."""
    try:
        import onnx
        from onnx import TensorProto, helper
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise SystemExit(
            "the 'onnx' package is required to (re)generate the fixture: "
            "python -m pip install onnx"
        ) from exc

    node = helper.make_node("Identity", [INPUT_NAME], [OUTPUT_NAME], name=NODE_NAME)
    input_info = helper.make_tensor_value_info(INPUT_NAME, TensorProto.FLOAT, INPUT_SHAPE)
    output_info = helper.make_tensor_value_info(OUTPUT_NAME, TensorProto.FLOAT, INPUT_SHAPE)
    graph = helper.make_graph([node], GRAPH_NAME, [input_info], [output_info])
    model = helper.make_model(
        graph,
        producer_name=PRODUCER_NAME,
        producer_version=PRODUCER_VERSION,
        opset_imports=[helper.make_opsetid("", OPSET_VERSION)],
    )
    model.ir_version = IR_VERSION
    # Drop the explicit empty opset domain so the bytes match the checked-in
    # fixture regardless of the onnx version (newer onnx serializes an explicit
    # empty `domain` field; the default ONNX domain is "" either way).
    for opset in model.opset_import:
        if opset.domain == "":
            opset.ClearField("domain")
    onnx.checker.check_model(model)
    return model.SerializeToString()


def encode_b64(model_bytes: bytes) -> str:
    return base64.b64encode(model_bytes).decode("ascii")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT,
                        help="where to write the base64 fixture (default: %(default)s)")
    parser.add_argument("--onnx-output", type=pathlib.Path, default=None,
                        help="optionally also write the raw .onnx binary here")
    parser.add_argument("--verify", action="store_true",
                        help="regenerate in memory and assert it matches --output; do not write")
    args = parser.parse_args(argv)

    model_bytes = build_model_bytes()
    encoded = encode_b64(model_bytes)

    if args.verify:
        existing = args.output.read_text().strip()
        if existing != encoded:
            print(f"FIXTURE MISMATCH: regenerated bytes differ from {args.output}", file=sys.stderr)
            return 1
        print(f"OK: regenerated fixture matches {args.output} ({len(model_bytes)} bytes)")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(encoded)
    print(f"wrote {args.output} ({len(model_bytes)} decoded bytes)")
    if args.onnx_output is not None:
        args.onnx_output.parent.mkdir(parents=True, exist_ok=True)
        args.onnx_output.write_bytes(model_bytes)
        print(f"wrote {args.onnx_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
